### ISSUE TITLE
Line breaks in tables are not preserved

### ISSUE THREAD

**Issue by Alagts** [TYPO3-Documentation/render-guides#568] opened 2024-05-21 08:23 UTC
**Issue description:** 
The line breaks should be preserved in order to enhance readability. In the screenshot you can see that the line breaks are omitted and therefore the structure of the content is partly lost. Here is the [link](https://docs.typo3.org/p/friendsoftypo3/extension-builder/main/en-us/_sources/GraphicalEditor/Index.rst.txt) to the page where I found the issue.

Here is a screenshot of the problem:
The red arrows show missing line breaks.
![preserve_linebreaks_table](https://github.com/TYPO3-Documentation/render-guides/assets/16323871/04c2e3fb-7b84-42d0-bd17-1e54d45aca48)

The source code can be found under this [link](https://docs.typo3.org/p/friendsoftypo3/extension-builder/main/en-us/_sources/GraphicalEditor/Index.rst.txt).

**Further thoughts about solving the problem:**
Of course if a word is too long it should be wrapped. But if a line break appears we should respect it (for example with a css property: white-space: pre-line ?). I would add also some space between the lines if there isn't space anyway.

**Comment by linawolf** [comment] 2024-05-21 17:29
Thanks for the report, this is a problem of parsing, not of styles. Related to https://github.com/TYPO3-Documentation/render-guides/issues/460

**Comment by jaapio** [comment] 2024-09-04 20:00
This is a duplicate of the mentioned issue by lina. I will close this issue as it's proven to be a duplicate.

**Closed by jaapio** 2024-09-04 20:00 UTC
Labels: duplicate
