### ISSUE TITLE
Sidebar navigation is not opened when a Document within subdirectory is rendered

### ISSUE THREAD

**Issue by garvinhicking** [TYPO3-Documentation/render-guides#81] opened 2023-11-16 11:59 UTC
Steps to reproduce:
* Render "Documentation" of repository
* Check a subpage like `Developers/Building/Index.html`
* Left navigation shows the menu state just like for the root `Index.html`

Expected output: 
* The menu should show the entries of "Developers" opened up directly

**Comment by linawolf** [comment] 2023-12-18 18:15
duplicate of https://github.com/TYPO3-Documentation/render-guides/issues/222

**Closed by linawolf** 2023-12-18 18:15 UTC
